services:
  - type: web
    name: real-estate-website
    runtime: docker
    repo: https://github.com/Anto7304/groupassignment
    branch: main
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: "postgresql://realestate_db_unx3_user:N7Z2dlsvmbFAIsR4hxengw1wjQwgXj06@dpg-d81nju83kofs73cu4b60-a.oregon-postgres.render.com/realestate_db_unx3"